### ISSUE TITLE
Verify ownership on beta.flathub.org

### ISSUE THREAD

**Issue by barthalion** [flathub/org.fedoraproject.MediaWriter#21]
We're preparing for the launch of beta.flathub.org, and would like to see your app verified as maintained by its developers. Currently, I've marked it as such manually, but it would be preferred to use one of the verification features. This can be initiated by logging it at https://beta.flathub.org/login with a GitHub account, pressing "Developer Settings" and following the instructions there.

**Comment by grulja** [comment]
Hi @barthalion, I can see:
`You'll need to prove that you have control of the app via a website on the app's domain or by checking access to the app's account on a source code hosting site.`

How do I do the other thing?

**Comment by barthalion** [comment]
I think the only method available will be website-based. It's tied to the ID, so it means proving "control" of fedoraproject.org. I can keep it marked as verified manually if Fedora sysadmins are difficult to work with!

**Comment by grulja** [comment]
@barthalion forwarding question from https://pagure.io/fedora-infrastructure/issue/11217#comment-851934:

>Does it have to be at that specific location? The reason why i am asking, is that it would be trivial to put a text file like >that at this location `https://apps.fedoraproject.org/.well-known/org.flathub.VerifiedApps.txt` which is still under the >fedoraproject.org domain.

**Comment by grulja** [comment]
The file now exists at: https://fedoraproject.org/.well-known/org.flathub.VerifiedApps.txt

@barthalion is there something else to do?

**Comment by barthalion** [comment]
Looks like it's been verified so no! Thanks!
