### ISSUE TITLE
runtime org.kde.Platform branch 6.6 is end-of-life

### ISSUE THREAD

**Issue by tobiasmicheler** [flathub/org.fedoraproject.MediaWriter#35]
Info: runtime org.kde.Platform branch 6.6 is end-of-life, with reason:
We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
org.fedoraproject.MediaWriter

**Comment by farribeiro** [comment]
The Platform was updated to 6.7

See #33

**Comment by farribeiro** [comment]
I asked the flathub Matrix to re-run the build

**Comment by farribeiro** [comment]
By the way, 6.8 runtime is available
