### ISSUE TITLE
Terrible GUI flicker

### ISSUE THREAD

**Issue by pabl0** [flathub/org.fedoraproject.MediaWriter#8]
When running on Debian 10, the main window of MediaWriter flickers so badly that the app is basically unusable. 

Difficult to explain, so I made a video recording of the effect:

https://seestieto.com/misc/bugs/Fedora-Mediawriter-flicker.mp4

`          ID: org.fedoraproject.MediaWriter
         Ref: app/org.fedoraproject.MediaWriter/x86_64/stable
        Arch: x86_64
      Branch: stable
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 6.0 MB
     Runtime: org.kde.Platform/x86_64/5.12
         Sdk: org.kde.Sdk/x86_64/5.12

      Commit: 846c936d00186b0e98739d9f6af37516f3328e70b5c34a311dd8eeec993424c5
      Parent: ce11a3ef67e2a8d2a6adeebbac14b380bf11f1f39d34abec54b6cc71c4ff246c
     Subject: Update to 4.1.3 (0fa051b5)
        Date: 2019-04-21 20:55:21 +0000
`

**Comment by eszlari** [comment]
Maybe this is fixed with a Qt / KDE runtime update.

Can you test the build from this PR: https://github.com/flathub/org.fedoraproject.MediaWriter/pull/7

**Comment by pabl0** [comment]
@eszlari , I can confirm that the flicker is gone with this build with runtime 5.14. Thanks!
